server.port: 8088

app:
    innov:
      ftp:
        user: sc0904102
        remoteHost: terminal.scloud.ru
        remotePort: 2121
        targetFolder: /INPUT/IM

management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

server:
  servlet:
    context-path: /btl

